import React, { useState, useEffect } from "react";
import ThreeScene from "./components/ThreeScene";
import TeacherSelector from "./components/TeacherSelector";
import SearchBar from "./components/SearchBar";
import CodePanel from "./components/CodePanel";
import ExplanationPanel from "./components/ExplanationPanel";
import Contact from "./components/Contact";
import axios from "axios";
import "./index.css";

// --- UPDATED: DYNAMIC API URL ---
// If VITE_API_URL is set (Production), use it. Otherwise use localhost (Development).
// Remove the trailing slash if it exists to avoid double slashes (//)
const API_BASE_URL = (import.meta.env.VITE_API_URL || "http://127.0.0.1:8000").replace(/\/$/, "");

export default function App() {
  const [teacher, setTeacher] = useState("female");
  const [loading, setLoading] = useState(false);
  const [isRecording, setIsRecording] = useState(false);
  const [isSpeaking, setIsSpeaking] = useState(false);
  const [view, setView] = useState("home");

  const [inputText, setInputText] = useState("");
  const [userQuery, setUserQuery] = useState("");
  const [explanation, setExplanation] = useState("");
  const [codeData, setCodeData] = useState(`# AI Guru J Ready.\n# Ask a question (e.g., "swap numbers") to start!`);

  const [audioUrl, setAudioUrl] = useState(null);
  const [lipSyncData, setLipSyncData] = useState(null);
  const [isMuted, setIsMuted] = useState(false);
  const [reloadTrigger, setReloadTrigger] = useState(0);
  const [audioEl] = useState(() => new Audio());

  // --- AUDIO PRIMING (Unlock for Mobile/Auto-play) ---
  useEffect(() => {
    const unlock = () => {
      audioEl.play().then(() => {
        audioEl.pause();
        audioEl.currentTime = 0;
      }).catch(() => { });
      document.removeEventListener("click", unlock);
      document.removeEventListener("touchstart", unlock);
    };
    document.addEventListener("click", unlock);
    document.addEventListener("touchstart", unlock);

    // --- AUDIO EVENT LISTENERS (Track Speaking State) ---
    const handleStart = () => setIsSpeaking(true);
    const handleEnd = () => setIsSpeaking(false);

    audioEl.addEventListener("play", handleStart);
    audioEl.addEventListener("playing", handleStart);
    audioEl.addEventListener("ended", handleEnd);
    audioEl.addEventListener("pause", handleEnd);

    return () => {
      document.removeEventListener("click", unlock);
      document.removeEventListener("touchstart", unlock);
      audioEl.removeEventListener("play", handleStart);
      audioEl.removeEventListener("playing", handleStart);
      audioEl.removeEventListener("ended", handleEnd);
      audioEl.removeEventListener("pause", handleEnd);
    };
  }, [audioEl]);

  async function sendToBackend(formData) {
    setLoading(true);
    setExplanation("Thinking...");
    setUserQuery("");
    setCodeData("# Generating code...");

    try {
      const resp = await axios.post(`${API_BASE_URL}/api/tutor/query/`, formData, {
        headers: { "Content-Type": "multipart/form-data" }
      });

      const data = resp.data;
      setUserQuery(data.user_query || "User Query");
      setExplanation(data.explanation || "Here is the explanation.");

      const validCode = data.code && data.code.trim().length > 0
        ? String(data.code)
        : "# The AI provided an explanation but no specific code snippet.";

      setCodeData(validCode);
      setLipSyncData(data.lip_sync || null);

      // Use the audio URL generated by the backend!
      if (data.audio_url) {
        setAudioUrl(data.audio_url);
      }

    } catch (e) {
      console.error("API Error:", e);
      setExplanation("Error connecting to AI Guru J backend. Please check the terminal.");
      setCodeData("# Connection Error.");
      setAudioUrl(null);
    } finally {
      setLoading(false);
    }
  }

  async function handleSubmitText(textOverride = null) {
    const textToSend = typeof textOverride === 'string' ? textOverride : inputText;
    if (!textToSend.trim()) return;

    // Update input text visual state if we are auto-submitting
    if (textOverride) setInputText(textOverride);

    const formData = new FormData();
    formData.append("text_query", textToSend);
    formData.append("teacher_gender", teacher);
    await sendToBackend(formData);

    // Clear after send
    setInputText("");
  }

  return (
    <div className="app-root">
      <nav className="top-nav">
        <div className="logo-container" onClick={() => setView("home")} style={{ cursor: 'pointer' }}>
          <span className="logo-3d">🧊</span>
          <span className="logo-text">AI Guru J</span>
        </div>
        <div className="nav-links">
          <a
            href="#"
            className={`nav-item ${view === "home" ? "active" : ""}`}
            onClick={(e) => { e.preventDefault(); setView("home"); }}
          >
            Home
          </a>
          <a
            href="#"
            className={`nav-item ${view === "contact" ? "active" : ""}`}
            onClick={(e) => { e.preventDefault(); setView("contact"); }}
          >
            Contact
          </a>
        </div>
      </nav>

      {view === "contact" ? (
        <Contact />
      ) : (
        <>
          <div className="top-right-selector">
            <div className="nav-controls">
              <button
                className="nav-control-btn mute-btn"
                onClick={() => setIsMuted(!isMuted)}
                title={isMuted ? "Unmute" : "Mute"}
              >
                {isMuted ? "🔈" : "🔊"}
              </button>
              <button
                className="nav-control-btn reload-btn"
                onClick={() => setReloadTrigger(prev => prev + 1)}
                title="Reload Voice"
              >
                🔄
              </button>
            </div>
            <TeacherSelector teacher={teacher} setTeacher={setTeacher} />
          </div>

          <div className="main-content-area">
            <div className="whiteboard-container">
              <div className="wb-panel-left">
                <CodePanel codeData={codeData} />
              </div>
              <div className="wb-panel-right">
                <ExplanationPanel explanation={explanation} userQuery={userQuery} />
              </div>
            </div>
            <div className="avatar-container">
              <ThreeScene
                teacher={teacher}
                lipSyncData={lipSyncData}
                audioUrl={audioUrl}
                isRecording={isRecording}
                loading={loading}
                isMuted={isMuted}
                reloadTrigger={reloadTrigger}
                audioEl={audioEl}
              />
            </div>
          </div>

          <div className="bottom-bar">
            <div className="search-bar-container">
              <SearchBar
                loading={loading}
                isSpeaking={isSpeaking}
                onStateChange={setIsRecording}
                onInputUpdate={setInputText}
                onSubmit={(text) => handleSubmitText(text)}
              />
            </div>

            <div className="text-input-container">
              <input
                type="text"
                className="text-input-field"
                placeholder="Type your question..."
                value={inputText}
                onChange={(e) => setInputText(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && handleSubmitText()}
                disabled={loading}
              />
              <button
                className="input-send-btn"
                onClick={handleSubmitText}
                disabled={loading}
              >
                {loading ? "..." : "➤"}
              </button>
            </div>
            <div className="bottom-icon sparkle">✨</div>
          </div>
        </>
      )}
    </div>
  );
}